### ISSUE TITLE
A fork?

### ISSUE THREAD

**Issue by SILENCE-GIVES-CONSENT** [irungentoo/openal-soft-tox#1]
Did you really fork openal-soft into openal-soft-tox instead of making PRs to the original project?
I already need openal-soft for many programs and now I'll have to install openal-soft-tox too, that's the exact same thing with a few lines of code added? What is this madness?

**Comment by irungentoo** [comment]
The only reason this is here is so people can easily find the sources of the version of openal currently being static linked to the Tox binaries.

It's more of a github fork than a real fork.
